services:
  snipeit_mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:5.6
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ${VOLUME_ROOT}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  snipeit:
    container_name: ${SNIPEIT_CONTAINER_NAME}
    image: snipe/snipe-it:latest
    restart: on-failure
    depends_on:
      - ${MYSQL_CONTAINER_NAME}
    env_file:
      - ./.env
    ports:
      - "${HTTP_PORT}:80"
      # - "80:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${VOLUME_ROOT}/snipeit:/var/lib/snipeit
      - ${VOLUME_ROOT}/snipeit-logs:/var/www/html/storage/logs
    links:
      - ${MYSQL_CONTAINER_NAME}
