services:
  mysql:
    container_name: snipeit-mysql
    image: mysql:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ${VOLUME_ROOT}/mysql:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 50

  snipeit:
    container_name: snipeit
    image: snipe/snipe-it:latest
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MAIL_PORT_587_TCP_ADDR
      - MAIL_PORT_587_TCP_PORT
      - MAIL_ENV_FROM_ADDR
      - MAIL_ENV_FROM_NAME
      - MAIL_ENV_ENCRYPTION
      - MAIL_ENV_USERNAME
      - MAIL_ENV_PASSWORD
      - APP_ENV
      - APP_DEBUG
      - APP_KEY
      - APP_URL
      - APP_TIMEZONE
      - TZ
      - APP_LOCALE
      - PHP_UPLOAD_LIMIT
    volumes:
      - ${VOLUME_ROOT}/snipeit:/var/lib/snipeit
      - ${VOLUME_ROOT}/snipeit-logs:/var/www/html/storage/logs
    links:
      - mysql
    ports: # FIXME: remove only used for testing
      - 8080:80
